# Generated by Django 2.2.2 on 2019-09-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_tree', '0004_auto_20190803_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecomment',
            name='comment_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='plain', max_length=30),
        ),
    ]
