# Generated by Django 2.2.7 on 2019-12-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_tree', '0005_auto_20190920_2317'),
        ('django_comments_tree', '0008_auto_20191027_2147'),
    ]

    operations = [
    ]
